version: '3.8'

services:
  php-app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html  # Monte le dossier du projet entier
      # Ne montez pas le dossier contenant la configuration Apache
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=heritage.local
      - DB_HOST=mysql
      - DB_NAME=mediatheque
      - DB_USER=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mediatheque
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: