INSERT INTO `book` (`id`, `titre`, `auteur`, `disponible`, `page_number`) VALUES 
(NULL, 'To Kill a Mockingbird', 'Harper Lee', '1', '324'),
(NULL, '1984', 'George Orwell', '1', '328'),
(NULL, 'Pride and Prejudice', 'Jane Austen', '1', '279'),
(NULL, 'The Great Gatsby', 'F. Scott Fitzgerald', '1', '180'),
(NULL, 'Moby-Dick', 'Herman Melville', '0', '635'),
(NULL, 'War and Peace', 'Leo Tolstoy', '1', '1225'),
(NULL, 'Crime and Punishment', 'Fyodor Dostoevsky', '0', '671'),
(NULL, 'The Catcher in the Rye', 'J.D. Salinger', '1', '214'),
(NULL, 'The Odyssey', 'Homer', '1', '541'),
(NULL, 'Brave New World', 'Aldous Huxley', '1', '288'),
(NULL, 'The Lord of the Rings', 'J.R.R. Tolkien', '0', '1178'),
(NULL, 'Jane Eyre', 'Charlotte Brontë', '1', '500'),
(NULL, 'Animal Farm', 'George Orwell', '1', '112'),
(NULL, 'The Brothers Karamazov', 'Fyodor Dostoevsky', '1', '796'),
(NULL, 'Wuthering Heights', 'Emily Brontë', '0', '416'),
(NULL, 'The Hobbit', 'J.R.R. Tolkien', '1', '310'),
(NULL, 'Fahrenheit 451', 'Ray Bradbury', '1', '194'),
(NULL, 'Les Misérables', 'Victor Hugo', '1', '1232'),
(NULL, 'The Divine Comedy', 'Dante Alighieri', '0', '798'),
(NULL, 'Dracula', 'Bram Stoker', '1', '418');