INSERT INTO `movie` (`id`, `titre`, `auteur`, `disponible`, `duration`, `genre`) VALUES 
(NULL, 'The Shawshank Redemption', 'Frank Darabont', '1', '2.2', 'Drama'),
(NULL, 'The Godfather', 'Francis Ford Coppola', '1', '2.9', 'Crime'),
(NULL, 'The Dark Knight', 'Christopher Nolan', '1', '2.3', 'Action'),
(NULL, 'Pulp Fiction', 'Quentin Tarantino', '0', '2.5', 'Crime'),
(NULL, 'Forrest Gump', 'Robert Zemeckis', '1', '2.2', 'Drama'),
(NULL, 'Inception', 'Christopher Nolan', '1', '2.5', 'Science Fiction'),
(NULL, 'Fight Club', 'David Fincher', '0', '2.3', 'Drama'),
(NULL, 'The Matrix', 'The Wachowskis', '1', '2.2', 'Science Fiction'),
(NULL, 'Goodfellas', 'Martin Scorsese', '1', '2.5', 'Crime'),
(NULL, 'The Silence of the Lambs', 'Jonathan Demme', '1', '2.0', 'Crime'),
(NULL, 'Schindler\'s List', 'Steven Spielberg', '1', '3.2', 'Drama'),
(NULL, 'The Green Mile', 'Frank Darabont', '1', '3.0', 'Drama'),
(NULL, 'Interstellar', 'Christopher Nolan', '1', '2.9', 'Science Fiction'),
(NULL, 'Se7en', 'David Fincher', '0', '2.1', 'Crime'),
(NULL, 'Gladiator', 'Ridley Scott', '1', '2.5', 'Action'),
(NULL, 'Jurassic Park', 'Steven Spielberg', '1', '2.1', 'Aventure'),
(NULL, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', '0', '2.9', 'Aventure'),
(NULL, 'The Lion King', 'Roger Allers', '1', '1.8', 'Aventure'),
(NULL, 'Titanic', 'James Cameron', '0', '3.2', 'Romance'),
(NULL, 'Saving Private Ryan', 'Steven Spielberg', '1', '2.9', 'Action');